### ISSUE TITLE
What's next for Harmonoid? & Release Goals

### ISSUE THREAD

**Issue by alexmercerind** [harmonoid/harmonoid#348]
## Release Goals

Greatly affected by my personal life e.g. study, schedule, exams, other projects, interview preparation & college.

**[Out Now • v0.3.4] 2022 Q4 - Part 1**

- [x] Ability to configure parameters (year, album artist & album name) which identify an album uniquely.
- [x] Remembering window position, size & maximized state on fresh start.
- [x] Ability to set custom libmpv options, properties & flags (#329).
- [x] Smoother animations (upstream from Flutter 3.3.x).
- [x] Smoother scrolling with trackpad/touchpad (upstream from Flutter 3.3.x).
- [x] Fixed/improved FLAC & OGG bitrate calculation/approximation.
- [x] Fix track order in `AlbumScreen`. Now accounts disc-number.
- [x] `AlbumTile` context menus (#339).
- [x] Fixed crash on Windows 7.
- [x] Fixed legacy `NowPlayingScreen`.
- [x] Fixed annoying line below window controls on Windows (rarely experienced on some PCs).
- [x] Rewrite custom window frame, more stable DPI-change handling, hit-box testing & fullscreen.
- [x] Use Win32 API to fetch `AppData` & default `Music` folder on Windows instead of environment variables.
- [x] Prevent data-redundancy in music library caching.
- [x] Improve "show in file explorer" behavior on Linux.
- [x] Improve Android launch speed.
- [x] Improve the quality of color palette extraction (further tweaks).
- [x] Better & performant URI & file path parsing.
- [x] Re-designed missing folders screen.
- [x] Add missing "Add to playlist" & "Shuffle" buttons on Android (at-places).
- [x] Enable Linux / Android-x86 touchscreen & mouse drag scroll (#342).
- [x] Old streaming recommendations behavior i.e. refresh on page revisit.
- [x] Fixed an issue that caused Harmonoid to request last-modified time stamps of all files already present in cache.
  This is a major issue. Now, cached last-modified time stamps are used.
  This will also improve start-up performance & safety with long file-paths on Windows. Apologies for the inconvenience.

**[Out Now • v0.3.5] 2022 Q4 - Part 2**

- [x] Migrate project to API changes in [`package:media_kit`](https://github.com/alexmercerind/media_kit).
- [x] Safer hyperlinks. Add null-check after lookup for album/artist in [`package:media_library`](https://github.com/alexmercerind/media_library) `HashSet`(s) (#366). 
- [x] Multiple genre support (not exposed yet).
- [x] Ability to disable all audio filters on Android. Some ROMs are having trouble.
- [x] Fixed NAS / SMB support on Windows.
- [x] Support for installing for current users only on Windows (#372).
- [x] Next/Previous buttons not greyed out in `ModernNowPlayingScreen` (#369).
- [x] Make fallback album arts configurable (#379).
- [x] Fixed missing thumbnail toolbar buttons on Windows.
- [x] Fixed opening file from file explorer causing Harmonoid window to become restored (if already maximized).
- [x] Fixed "CANCEL" button on minimum file size dialog popping `Navigator` on the wrong `BuildContext`.
- [x] Sticky Miniplayer option for Android.
- [x] Add `Play all` button next to `Shuffle` on Albums & Artists screens to play them orderly.
- [x] Disable GTK headerbar on GNOME (#380).
- [x] Fixed unresponsive window when closing window on **Windows 7 only**.
- [x] Fixed issue that caused opening music from File Explorer making Harmonoid restored (if maximized) on Windows.
- [x] Aligned text & label inside various `TextField`(s).
- [x] Fixed issue that made manually entering values in "Control Panel" difficult.

**[Under Progress] 2022 Q4 - Part 3**

- [x] ~~Delegate recursive directory listing & metadata fetching to [`MediaStore`](https://developer.android.com/reference/android/provider/MediaStore) use in [`package:media_library`](https://github.com/alexmercerind/media_library) on Android 10+.~~
- [ ] "Play next".
- [ ] Replay Gain support for Windows & Linux.
- [ ] Drag & drop support (#371).
- [ ] Add "album artist" filter in Artist tab (#365).
- [ ] Use rubberband as default audio filter instead of scaletempo (if available on system) (#368).
- [ ] Support for system-wide Android equalizer (#374).

**[Future Scope] 2023 Q1**

_Patreon, GitHub Sponsors & supporters exclusive [one-time]._

- [ ] Android app for controlling & browsing music on desktop app.
- [ ] Folder view.
  - Directory sorting parameters.
  - View types: tiles, icons, list.
  - Ability to add a complete folder to "now playing" or a playlist. 
- [x] Genre view (with multiple genre support / tag split).

**[Future Scope] 2023 Q2**

- [ ] Universal Material You / Material Design 3 music widget (not specific to Harmonoid).

**Somewhere along the line**

- [ ] Last.fm scrobbling.
- [ ] Mini-window mode.
- [ ] Minimization to system tray.
- [x] Improved playlist specification.
- [ ] Plugin API.
- [ ] Windows 11 `IExplorerCommand` integration.
- [x] Re-design illustrations & empty state artworks.
- [x] Ability to disable animations (#341).
- [ ] Expose theme configuration & add support for third-party themes.
- [ ] Enable ICECAST metadata support for online URLs & cache cover art.
- [x] Consistent & precise Material You / Material Design 3 implementation.
- [ ] Improved UI for tablets.

**Seems impossible based on my availability**

- [ ] #315.
- [ ] #375.
- [ ] #277 

<hr>

Along the way, account for the improvements made in Flutter itself.

## Personal Thoughts

I built Harmonoid for myself. I have spent a large amount of time on configuring small bits & pieces of the UI & animations. You may know more about this in ["Why"](https://github.com/harmonoid/harmonoid/blob/master/README.md#why) section of the README. Holding accountability of a software, ensuring that the implemented features work perfectly & UI feels good / consistent / nicely-put-together, is a really big challenge. Still, I feel it's in a good state now.

Recently, I have been really active in terms of development on Harmonoid (and various modules as part of it). I still fix bugs within few hours of report (now things are really stable though) from the users, usability is important.

However, I've decided to _slow down_.

I recently had a realization (after having a talk with my family & friends) that I've been working on this like a _maniac_. I should instead study my subjects in detail, prepare for interviews, learn more skills & work for my future. In general, I'm missing out my life as-well. Now, I'm back in college & I also have a part-time job along the way. Harmonoid isn't going anywhere. Unfortunately, the amount of time that I've spent on Harmonoid is far-far more than a "portfolio project" deserves. A "portfolio project" doesn't have any users or any responsibility of holding accountability.

When adding a new feature, it's now a trade-off between:
_"The effort it would take."_ V.S. _"The actual improvement in experience it would bring."_

There are project Patreon & supporters (_love you guys_), who deserve some exclusive features for their valuable early support to the project. Let's see where this goes.

Then, there are people who ask for crazy features. Like... c'mon I'm a single developer with little-to-no funding & backing. There's no way I can compete with a multibillion-dollar organization. It's just that I worked hard on this software, after missing out on a lot of moments of my life with my family & friends to hold "somewhere-near" credibility & quality.

Anyways, good things take time to build (_years of time_).
And I've just started, there's a lot more to come... as long as I don't suffer burnout.

Thanks!

<hr>

_If you have any question, feel free to ask in a comment below._

**Comment by palijn** [comment]
Most portfolio projects are just that, things you put in a portfolio and never attend to.
Harmonoid is a **masterpiece** . Be proud of it.
Very few developers manage such feats alone. You can show for real that you stand out of the crowd.
This project should speak volumes in your interviews about your abilities : smart _and_ hard work, attention to the details, dedication, close following of specifications/standards, catering to the end user experience, ability to implement things beyond the drawing board.
Thanks for sharing this software with the world.
Please take care of yourself and keep the vibe going.

**Comment by pktiuk** [comment]
Hello,    
I've seen that there is not much activity in the code of harmonoid recently.    
What is going on? Lack of time or your focus is now shifted to something else?

**Comment by senolfndk** [comment]
when is the new version

**Comment by alexmercerind** [comment]
Hey @tamha-rein, thanks! Just busy with track of life.

You should try out the latest [snapshot](https://github.com/harmonoid/snapshots/releases/tag/snapshot) build. I have been working on bunch of things in silence over at #475. I hope to release it soon, after a big gap of 2 years. A lot of things have been improved.

**Comment by alexmercerind** [comment]
Closing this issue now. We (community) primarily discuss future plans in our Discord.

Thanks!

**Comment by jo-chemla** [comment]
Thanks for releasing 3.10.0! 

Quick note, it might be good for Harmonoid to automatically push new releases to winget-pkgs via a github action workflow base on the winget-releaser v2 action. In the meantime, I have to manually push updates via Komac, see example PR https://github.com/microsoft/winget-pkgs/pull/270186. 

The fact that the installer is not reachable via a permanent url (one url per version) means the `winget install harmonoid` command might fail due to mismatching MD5 hash. I'm currently using https://github.com/harmonoid/snapshots/releases/download/snapshot/harmonoid-windows-setup.exe
